src/Entity/Booking.php
<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 *
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{

    /**
     *
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     *
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="La date doit etre au bon format !")
     * @Assert\GreaterThan("today",message="date must be
     * greater than today",groups={"front"})
     * 
     * 
     */
    private $startDate;

    /**
     *
     * @ORM\Column(type="datetime")
     * 
     * @Assert\Date(message="La date doit etre au bon format !")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de depart must
     * be greater than la date d'arriver")
     */
    private $endDate;

    /**
     *
     * @ORM\Column(type="datetime")
     *
     *
     */
    private $createdAt;

    /**
     *
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    public function isBookableDates()
    {
        // il faut connaitre les dates qui impossible
        $notAvailableDays = $this->ad->getNotAvailableDates();

        // comparer les dates choisies avec les dates impossibles
        $bookingDays = $this->getDays();

        // tableaux de chaine de caracters de mes journees d
        // reservation
        $days = array_map(function ($day) {
            return $day->format('Y-m-d');
        }, $bookingDays);

        $notAvailable = array_map(function ($day) {
            return $day->format('Y-m-d');
        }, $notAvailableDays);
        
            foreach ($days as $day){
                if(array_search($day, $notAvailable)!==false) return false;
                
            }
        
       return true; 
    }

    /**
     * permet de recuperer les journees de la reservation
     */
    public function getDays()
    {
        $resultat = range($this->getStartDate()->getTimestamp(),
            $this->getEndDate()->getTimestamp(),
            24 * 60 * 60 );

        $days = array_map(function ($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        },$resultat);
        return $days;
    }

    /**
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        if (empty($this->amount)) {
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function getDuration()
    {
        $dif = $this->endDate->diff($this->startDate);
        return $dif->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Entity\Role;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"},
 * message="Adresse email existe deja !!!!")
 * 
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="renseigner votre prenom ")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="renseigner votre nom ")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="email deja utileser ")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez donner une URL valide")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     * 
     */
    private $hash;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10,minMessage="L'introduction doit avoir plus de 10 caracteres")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=10,minMessage="La description doit avoir plus de 10 caracteres")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;
    
    /**
     * 
     * @Assert\EqualTo(propertyPath="hash",message="confirmation !== mot de passe !")
     */
    private $confirmPassword;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;
    
    
    
    public function getFullName(){
        return "{$this->firstName} {$this->lastName}";
    }
    
    
    /**
     * @return mixed
     */
    public function getConfirmPassword()
    {
        return $this->confirmPassword;
    }

    /**
     * @param mixed $confirmPassword
     */
    public function setConfirmPassword($confirmPassword)
    {
        $this->confirmPassword = $confirmPassword;
    }

    /**
     * permet d'initialiser le slug a partir de l'entity
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     */
    public function initialiseSlug(){
        if(empty($this->slug)){
            $slugify=new Slugify();
            $this->slug=$slugify->slugify($this->firstName." ".$this->lastName);
        }
        
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }
    public function getPassword()
    {return $this->hash;}

    public function eraseCredentials()
    {}

    public function getSalt()
    {}

    public function getRoles() {
        $roles=$this->userRoles->map(function($role){
            return $role->getTitle();
        })->toArray();
        
        $roles[]='ROLE_USER';
       
        
        return $roles;
    }

        
    public function getUsername()
    {return $this->email;}

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    
    
    
    
    
}

src/Form/BookingType.php
<?php
namespace App\Form;

use App\Entity\Booking;
use App\Form\DataTransformer\FrenshToDateTimeTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;



class BookingType extends ApplicationType
{
    private $transformer;
    public function __construct(FrenshToDateTimeTransformer $transformer){
        $this->transformer=$transformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('startDate', TextType::class, $this->getconfig("Date d'arrivée", "Date d'arrivée"))
            ->add('endDate', TextType::class, $this->getconfig("Date de depart", "Date de depart"))
            ->add("comment", TextareaType::class, $this->getconfig(false, "Si vous avez un commantaire n'hesitez pas a me faire part !", [
            "required" => false
        ]));
            
          $builder->get('startDate')->addModelTransformer($this->transformer)  ;
          $builder->get('endDate')->addModelTransformer($this->transformer)  ;
            
    }

    
    
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            'validation_groups'=>["front","Default"]
        ]);
    }
}

src/Controller/BookingController.php
<?php
namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{

    /**
     * Permet de reserver une annonce
     *
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     */
    public function index(Ad $ad, Request $request, EntityManagerInterface $manager)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking,[
            'validation_groups'=>["front","Default"]
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $booking->setBooker($user)
                    ->setAd($ad);
                    
            //si les dates ne sont pas dispo
                    if(!$booking->isBookableDates()){
                        $this->addFlash("warning",
                            "la date choisie est deja prise");
                    }
                    
            //sinon   
                    else{
            $manager->persist($booking);
            $manager->flush();
            return $this->redirectToRoute("booking_show",[
                'id'=>$booking->getId(),
                'withAlert'=>true
            ]);
        }
        }

        return $this->render('booking/book.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }
    
    
    
    
    
    
    
    /**
     * Permet d'afficher la page d'une reservation
     * @Route("/booking/{id}" ,name="booking_show")
     */
    public function showB(Booking $booking,Request $request,EntityManagerInterface $manager){
        $comment=new Comment();

        $form=$this->createForm(CommentType::class,$comment);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $comment->setAd($booking->getAd())
                    ->setAuthor($this->getUser());

            $manager->persist($comment);
            $manager->flush();
            $this->addFlash('success',"Votre a bien été pris en compte");
            
        }

        
        return $this->render('booking/show.html.twig',[
           'booking'=>$booking ,
           'form'=>$form->createView()
        ]);
    }
    
    
    
    
    
    
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}
reserver l'annonce
{{ ad.title }}

{% endblock %}


{%   block stylesheets  %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />

{% endblock %}


{% block body %}

<div class="container">
	<h1>
		Reserver l'annonce
		<em>{{ ad.title }}</em>
	</h1>
	<p>
		Vous etes sur le point de reserver le bien de <strong>{{ ad.author.fullName }}</strong>
		,dites nous tout on s'uccupe du reste !
	</p>

	{{ form_start(form) }}
	<div class="alert alert-light">
		<h4>Dites nous les dates qui vous interessent !</h4>


		<div class="row ">
			<div class="col">
				{{ form_row(form.startDate) }}
			</div>

			<div class="col">
				{{ form_row(form.endDate) }}
			</div>

		</div>
		<h4 class="mt-3">Montant du sejour : <span id="amount">...</span> &euro;</h4>
	<span id="days">...</span> nuit(s) à {{ ad.price | number_format(2,',',' ' ) }}&euro; / nuit
	
	<h2 class="mt-3">Si vous avez un commantaire  !</h2>
	{{ form_row(form.comment) }}
	

	</div>
	
	
	<h2 class="mt-3" >vous avez terminé</h2>
	
	<button type="submit" class="btn btn-success">Reservez</button>
	
	{{ form_end(form) }}
	
</div>
{% endblock %}





{%   block javascripts  %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" ></script>
 
 <script> 

$(document).ready(function(){
	$('#booking_startDate, #booking_endDate').datepicker({
		format: 'dd/mm/yyyy',
		datesDisabled:[{% for day in ad.NotAvailableDates %}
								"{{ day.format('d/m/Y') }}",				
		                {% endfor %},
		               
		],
		 startDate: new Date()
	
		});
	$('#booking_endDate,#booking_startDate').on('change',calculateAmount);
})


function calculateAmount(){
	//On chope les dates
 //  
	const endDate=new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));
	const startDate=new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));
	
	if(startDate && endDate && startDate < endDate){
		const interval=endDate.getTime()-startDate.getTime();
		const days= interval/(24*60*60*1000);
		const amount=days*{{ ad.price }};
		
		$('#days').text(days);
		$('#amount').text(amount);
		
	}
	
}


  </script>
 
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Reservation n°{{ booking.id }} 
{% endblock %}

{% block body %}
{% set ad =booking.ad %}
{% set author =ad.author %}


<div class="container">
	<h1 class="my-5">Votre reservation n°{{ booking.id }}     </h1>
	
	{% if app.request.query.get('withAlert') %}
	
	<div class="alert alert-success">
	<h4 class="alert-heading">Bravo !</h4>
	<p>Votre reservation aupres de 
		<strong>
			<a href="{{path('user_show',{'slug':author.slug})}}">{{author.fullName}} </a>
		</strong>pour l'annonce: 
		<strong>
			<a href="{{path('ads_show',{'slug':ad.slug})}}">{{author.fullName}} </a>
		</strong>a bien été prise en compte
	</p>
	
	</div>
	
	{% endif %}

	<div class="row">
		<div class="col">
			<div class="alert alert-light">
				<h2>Details</h2>
				<dl class="row">
					<dt class="col-md-4">Numero</dt>
					<dd class="col-md-8">{{ booking.id }}</dd>
					<dt class="col-md-4">Date d'arrivée</dt>
					<dd class="col-md-8">{{ booking.startDate | date('d/m/y') }}</dd>
					<dt class="col-md-4">Date de depart</dt>
					<dd class="col-md-8">{{ booking.endDate | date('d/m/y') }}</dd>
					<dt class="col-md-4">Nombre de nuits</dt>
					<dd class="col-md-8">{{booking.duration}}</dd>
					<dt class="col-md-4">Montant total</dt>
					<dd class="col-md-8">{{ booking.amount | number_format(2,',',' ' )}} &euro;</dd>
					<dt class="col-md-4">Commentaire</dt>
					<dd class="col-md-8">{{ booking.comment |default('Aucun commantaire') }}</dd>
				</dl>
				<hr>
				
				<h2 class="alert-heading">Votre hote</h2>
				
				
				<div class="row mb-3">
					<div class="col-3">
						<img src="{{author.picture}}" class="avatar avatar-midium">
					</div> 
					<div class="col">
						<h4><a href="{{path('user_show',{'slug':author.slug})}}">
						{{author.fullName }}</a></h4>
						<span class="badge badge-primary">{{author.ads|length}} annonces</span>
					
					</div>
					
				</div>
				{{author.description|raw}}
					<a class="btn btn-primary" href="{{path('user_show',{'slug':author.slug})}}">
						plus d'infos sur {{author.firstName }}</a>
				
			</div>

			<div class="alert alert-light" id="comment">
				<h2 class="alert-heading">Votre avis compte !</h2>
				{% if date() > date(booking.endDate) %}
					{% set comment = booking.ad.commentFromAuthor(app.user) %}
					{% if comment is not null %}
						<blockquote>
							{{comment.content}}						
						</blockquote>	
						<strong>Note :</strong>
						{% include "partials/rating.html.twig" 
						with { 'rating':comment.rating } %} 
					{% else %}
						{{form_start(form)}}
						{{form_widget(form)}}
						<button type="submit" class="btn btn-success">Commenter</button>
						{{form_end(form)}}
					{% endif %}	

				{% else %}
					<p>	Vous ne pourrez pas noter cette annonce tant que 
						votre reservation n'est pas terminer!!
					</p>
				{% endif %}
			</div>		



		</div>
		
		
		<div class="col">
			<div class="alert alert-light">
			<h2 class="alert-heading">Votre hebergement:</h2>
			
			<h4> 
				<a class="btn btn-primary" href="{{path('ads_show',{'slug':ad.slug})}}">
						{{ad.title }}</a>
			</h4>
			<img alt="image de {{ad.title}}" src="{{ad.coverImage}}" class="img-fluid">
			{{ad.content|raw}}
			
			<a class="btn btn-primary" href="{{path('ads_show',{'slug':ad.slug})}}">
						plus d'informations</a>
			</div>
		
		</div>


	</div>


</div>


{% endblock %}